services:

  postgres:
    image: postgres:17

    container_name: postgres-shorturl

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10    

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:

    build:
      context: ./backend

    container_name: shorturl-api

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8080:8080"

    env_file:
      - .env

    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

  frontend:

    build:
      context: ./frontend

    container_name: shorturl-front

    depends_on:
      - backend

    ports:
      - "3000:80"

volumes:
  postgres_data: